import "./Calendar.css";
import { HabitsDay } from "../Habits/HabitsDay";

export function Calendar(): JSX.Element {
  const week: string[] = ["D", "S", "T", "Q", "Q", "S", "S"];

  return (
    <div className="calendar">
      <div>
        {week.map((day, index) => {
          return <div key={index}>{day}</div>;
        })}
      </div>
      <div>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
        <HabitsDay/>
      </div>
    </div>
  );
}
